--- TABLE test_table
DROP TABLE IF EXISTS "test_table" CASCADE;
CREATE TABLE "test_table" (
  "id" SERIAL,
  "column_1" INTEGER,
  "column_2" TEXT,
  "column_3" TEXT,
  "column_4" TEXT,
  "column_5" TEXT,
  "column_6" TEXT,
  "column_7" TEXT,
  "column_8" TEXT,
  "column_9" TEXT,
  "column_10" TEXT,
  "column_11" TEXT,
  "column_12" TEXT,
  "column_13" TEXT,
  "column_14" TEXT,
  "column_15" TEXT,
  "column_16" TEXT,
  "column_17" TEXT,
  "column_18" TEXT,
  "column_19" TEXT,
  "column_20" TEXT,
  "column_21" TEXT,
  "column_22" TEXT,
  "column_23" TEXT,
  "column_24" TEXT,
  "column_25" TEXT,
  "column_26" TEXT,
  "column_27" TEXT,
  "column_28" TEXT,
  "column_29" TEXT,
  "column_30" TEXT,
  "updated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY  ("id")
);
